"""Natural-language task templates with gold parameters, split by template.

Templates never appear in more than one split, so no phrasing seen in
training is used to report test accuracy.
"""
from __future__ import annotations

import random

from .tasks import PARSERS, DEFAULTS
from .tools import CATEGORIES, POLICIES, QUARTERS, REGIONS

_ORD = {"Q1": "first", "Q2": "second", "Q3": "third", "Q4": "fourth"}
_PRODUCTS = {"electronics": ("laptop", "phone", "tablet", "camera"), "apparel": ("shirt", "jacket", "dress"),
             "furniture": ("sofa", "chair", "table"), "groceries": ("grocery order", "fresh produce box"),
             "books": ("book", "novel", "textbook"), "toys": ("toy", "puzzle", "doll")}
_ACTIONS = {"returns": "return", "warranty": "make a warranty claim on", "cancellation": "cancel an order for",
            "exchange": "exchange", "price_match": "request a price match on", "damage_claim": "file a damage claim for"}
_ITEMS = ("notebook", "pen", "mug", "cable", "lamp", "bottle", "folder")


def _money(amount):
    return f"{amount:,}"


FINANCE = [
    lambda p: f"Convert ₹{_money(p['amount'])} to USD and compute the monthly EMI for {p['months']} months at {p['annual_rate']}% annual interest.",
    lambda p: f"I am borrowing INR {p['amount']} for {p['months']} months at {p['annual_rate']}% per year. What is my monthly EMI in US dollars?",
    lambda p: f"What would the EMI be in USD on a loan of Rs. {_money(p['amount'])} over {p['months']} months with an annual rate of {p['annual_rate']}%?",
    lambda p: f"Loan amount: ₹{_money(p['amount'])}. Term: {p['months']} months. Interest: {p['annual_rate']}% p.a. Give the monthly payment in USD.",
    lambda p: f"Compute the USD monthly installment for a {p['months']}-month loan of INR {_money(p['amount'])} at {p['annual_rate']}% interest.",
    lambda p: f"My cousin needs ₹{_money(p['amount'])} repaid over {p['months'] // 12} years at {p['annual_rate']}%; what's the monthly EMI in dollars?",
    lambda p: f"Estimate the EMI in USD: principal INR {p['amount']}, {p['annual_rate']}% yearly rate, {p['months']} months.",
    lambda p: f"{p['amount'] // 1000}k rupees borrowed at {p['annual_rate']}% for {p['months']} months. What is the monthly EMI in USD?",
    lambda p: f"Please calculate the dollar EMI for a ₹{_money(p['amount'])} loan, {p['months']} months, {p['annual_rate']}% annual interest.",
    lambda p: f"If I take Rs. {p['amount'] / 100000:g} lakh at {p['annual_rate']}% for {p['months']} months, how much is each monthly payment in USD?",
    lambda p: f"A customer financed INR {_money(p['amount'])} for {p['months']} months at an annual rate of {p['annual_rate']}%. Report the EMI converted to USD.",
    lambda p: f"Work out the monthly EMI (USD) for borrowing {p['amount'] // 1000}k rupees over {p['months'] // 12} years at {p['annual_rate']}% interest.",
]
SQL = [
    lambda p: f"What is the total {p['metric']} for the {p['region']} region in Q{p['quarter'][1]}?" if p["metric"] == "revenue" else f"How many units did the {p['region']} region sell in Q{p['quarter'][1]}?",
    lambda p: f"Report the total sales revenue in the {p['region']} region for the {_ORD[p['quarter']]} quarter." if p["metric"] == "revenue" else f"Report the number of units sold in the {p['region']} region for the {_ORD[p['quarter']]} quarter.",
    lambda p: f"Sum the revenue from {p['region']}ern stores in Q{p['quarter'][1]}." if p["metric"] == "revenue" else f"Sum the units sold by {p['region']}ern stores in Q{p['quarter'][1]}.",
    lambda p: f"Total revenue, {p['region']} region, quarter Q{p['quarter'][1]}?" if p["metric"] == "revenue" else f"Total units, {p['region']} region, quarter Q{p['quarter'][1]}?",
    lambda p: f"How much revenue did we book in the {p['region']} territory during Q{p['quarter'][1]}?" if p["metric"] == "revenue" else f"How many units did we ship in the {p['region']} territory during Q{p['quarter'][1]}?",
    lambda p: f"Count the {p['metric']} for {p['region']} in the {_ORD[p['quarter']]} quarter." if p["metric"] == "units" else f"Add up {p['region']} revenue for the {_ORD[p['quarter']]} quarter.",
    lambda p: f"Give me {p['region']} region {p['metric']} for Q{p['quarter'][1]} from the sales table.",
    lambda p: f"Query the sales database: {p['metric']} in the {p['region']} region, Q{p['quarter'][1]}.",
    lambda p: f"Pull the {_ORD[p['quarter']]}-quarter revenue figure for {p['region']}." if p["metric"] == "revenue" else f"Pull the {_ORD[p['quarter']]}-quarter units figure for {p['region']}.",
    lambda p: f"What were total {p['metric']} for {p['region']} in Q{p['quarter'][1]}?",
    lambda p: f"Calculate the {p['metric']} generated by the {p['region']} region in Q{p['quarter'][1]}." if p["metric"] == "revenue" else f"Calculate the units sold by the {p['region']} region in Q{p['quarter'][1]}.",
    lambda p: f"In Q{p['quarter'][1]}, how many units were sold in the {p['region']}ern market?" if p["metric"] == "units" else f"In Q{p['quarter'][1]}, how much revenue came from the {p['region']}ern market?",
]
DOC_QA = [
    lambda p: f"How many days do I have to {_ACTIONS[p['policy']]} a {p['product']}?",
    lambda p: f"What is the deadline, in days, to {_ACTIONS[p['policy']]} a {p['product']}?",
    lambda p: f"Within how many days can a customer {_ACTIONS[p['policy']]} a {p['product']} after delivery?",
    lambda p: f"According to store policy, how long (in days) can I wait before I {_ACTIONS[p['policy']]} my {p['product']}?",
    lambda p: f"I bought a {p['product']}. How many days do I get to {_ACTIONS[p['policy']]} it?",
    lambda p: f"Look up the policy: number of days allowed to {_ACTIONS[p['policy']]} a {p['product']}.",
    lambda p: f"Tell me the time limit in days to {_ACTIONS[p['policy']]} a {p['product']}.",
    lambda p: f"Per our documentation, a shopper wants to {_ACTIONS[p['policy']]} a {p['product']}. What is the window in days?",
    lambda p: f"Can you check how many days someone has to {_ACTIONS[p['policy']]} a {p['product']}?",
    lambda p: f"What's the allowed period in days to {_ACTIONS[p['policy']]} a {p['product']}?",
    lambda p: f"A client asks how many days they have to {_ACTIONS[p['policy']]} a {p['product']}. Answer from the policy documents.",
    lambda p: f"From the policy corpus, find the days allowed to {_ACTIONS[p['policy']]} a {p['product']}.",
]
MATH = [
    lambda p: f"Buy {p['quantity']} {p['item']}s at ${p['unit_price']} each with a {p['discount_pct']}% discount. What is the total?",
    lambda p: f"What do {p['quantity']} {p['item']}s cost at ${p['unit_price']} apiece after a {p['discount_pct']}% discount?",
    lambda p: f"A shop sells {p['item']}s for ${p['unit_price']}. If I purchase {p['quantity']} with {p['discount_pct']}% off, what do I pay?",
    lambda p: f"Total cost of {p['quantity']} {p['item']}s priced at {p['unit_price']} dollars each, minus a {p['discount_pct']}% discount?",
    lambda p: f"Order: {p['quantity']} x {p['item']} @ ${p['unit_price']}, discount {p['discount_pct']}%. Final total?",
    lambda p: f"I need {p['quantity']} {p['item']}s. They are ${p['unit_price']} each and there's a {p['discount_pct']}% coupon. How much in total?",
    lambda p: f"Calculate the bill for {p['quantity']} {p['item']}s at ${p['unit_price']} per unit with {p['discount_pct']}% off.",
    lambda p: f"Price out {p['quantity']} {p['item']}s at ${p['unit_price']} each, applying a {p['discount_pct']}% promotion.",
    lambda p: f"With a {p['discount_pct']}% member discount, what do {p['quantity']} {p['item']}s at ${p['unit_price']} each cost?",
    lambda p: f"Find the total for {p['quantity']} {p['item']}s selling at ${p['unit_price']} a piece, after {p['discount_pct']}% off.",
    lambda p: f"How much will {p['quantity']} {p['item']}s cost if each is ${p['unit_price']} and a {p['discount_pct']}% discount applies?",
    lambda p: f"Purchase {p['quantity']} {p['item']}s at {p['unit_price']} dollars each; apply a {p['discount_pct']}% discount and give the total.",
]
TEMPLATES = {"finance": FINANCE, "sql": SQL, "doc_qa": DOC_QA, "math": MATH}
# 8 train / 2 validation / 2 test templates per family (by index).
SPLIT_INDEXES = {"train": range(0, 8), "validation": range(8, 10), "test": range(10, 12)}


def sample_params(family: str, rng: random.Random) -> dict:
    if family == "finance":
        return {"amount": rng.randrange(2, 40) * 5000, "months": rng.choice([12, 24, 36, 48, 60]),
                "annual_rate": rng.choice([6, 7.5, 8, 9, 10.5, 11, 12, 13.5]),
                "base_currency": "INR", "target_currency": "USD"}
    if family == "sql":
        return {"region": rng.choice(REGIONS), "metric": rng.choice(["revenue", "units"]), "quarter": rng.choice(QUARTERS)}
    if family == "doc_qa":
        category = rng.choice(CATEGORIES)
        return {"policy": rng.choice(POLICIES), "category": category, "product": rng.choice(_PRODUCTS[category])}
    return {"quantity": rng.randint(2, 40), "unit_price": rng.choice([3, 4.5, 6, 8, 12, 15, 19.5, 24, 35, 60]),
            "discount_pct": rng.choice([5, 10, 12.5, 15, 20, 25]), "item": rng.choice(_ITEMS)}


def render(family: str, template_index: int, params: dict) -> tuple[str, dict]:
    """Return (prompt, gold params). Display-only fields are dropped from the gold."""
    prompt = TEMPLATES[family][template_index](params)
    gold = {key: value for key, value in params.items() if key in DEFAULTS[family]}
    parsed = {**DEFAULTS[family], **PARSERS[family](prompt)}
    if any(parsed.get(key) != value for key, value in gold.items()):
        raise AssertionError(f"Template {family}/{template_index} is not parseable: {prompt!r} -> {parsed} vs {gold}")
    return prompt, gold


def generate_tasks(per_family: int, seed: int = 42) -> list[dict]:
    """Generate tasks round-robin over templates; split is fixed by template index."""
    rng = random.Random(seed)
    tasks = []
    for family in TEMPLATES:
        for case in range(per_family):
            index = case % len(TEMPLATES[family])
            split = next(name for name, indexes in SPLIT_INDEXES.items() if index in indexes)
            for _ in range(50):
                params = sample_params(family, rng)
                try:
                    prompt, gold = render(family, index, params)
                    break
                except AssertionError:
                    continue
            else:
                raise AssertionError(f"Could not render template {family}/{index}")
            day = 3 + case % 25
            tasks.append({"family": family, "template_id": f"{family}-t{index:02d}", "split": split,
                          "prompt": prompt, "params": gold, "frozen_at": f"2026-10-{day:02d}T12:00:00+00:00"})
    return tasks


# --------------------------------------------------------------------------- harder variants
# Numbers in words, distractor numbers and conflicting hints. Used for natural-failure
# experiments with real local models only; the gold answer still comes from the params.
_WORDS = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six", 7: "seven", 8: "eight", 9: "nine",
          10: "ten", 11: "eleven", 12: "twelve", 13: "thirteen", 14: "fourteen", 15: "fifteen", 16: "sixteen",
          17: "seventeen", 18: "eighteen", 19: "nineteen", 20: "twenty", 25: "twenty-five", 30: "thirty", 40: "forty"}


def _words(n):
    n = int(n)
    if n in _WORDS:
        return _WORDS[n]
    if n % 1000 == 0 and n // 1000 in _WORDS:
        return f"{_WORDS[n // 1000]} thousand"
    return str(n)


HARD = {
    "finance": [
        lambda p: f"I need the monthly payment, in dollars, on a loan of {_words(p['amount'])} rupees over {_words(p['months'] // 12)} years at {p['annual_rate']} percent a year.",
        lambda p: f"My bank quoted 15% last month, but the agreed rate is {p['annual_rate']}%. EMI in USD for INR {p['amount']} over {p['months']} months?",
    ],
    "math": [
        lambda p: f"{_words(p['quantity']).capitalize()} {p['item']}s cost {p['unit_price']} dollars apiece; with a {p['discount_pct']} percent discount, what is the total?",
        lambda p: f"Last time I bought 3 {p['item']}s. This time I need {p['quantity']} at ${p['unit_price']} each, {p['discount_pct']}% off. Total?",
    ],
    "sql": [
        lambda p: f"The 2025 report said 999 units, but what does the database say for {p['metric']} in the {p['region']} region in Q{p['quarter'][1]}?",
        lambda p: f"Ignoring other regions, give {p['metric']} for {p['region']}ern stores, quarter Q{p['quarter'][1]} only.",
    ],
    "doc_qa": [
        lambda p: f"An old FAQ says 90 days, but under the current policy how many days do I have to {_ACTIONS[p['policy']]} a {p['product']}?",
        lambda p: f"My friend got 7 extra days last year. Per today's policy, how many days are allowed to {_ACTIONS[p['policy']]} a {p['product']}?",
    ],
}


def generate_hard_tasks(per_family: int, seed: int = 7) -> list[dict]:
    rng = random.Random(seed)
    tasks = []
    for family, templates in HARD.items():
        for case in range(per_family):
            index = case % len(templates)
            params = sample_params(family, rng)
            if family == "finance":
                params["amount"] = rng.choice([10000, 20000, 25000, 40000])
                params["months"] = rng.choice([12, 24, 36])
            if family == "math":
                params["quantity"] = rng.choice([2, 5, 8, 12, 15, 20])
            prompt = templates[index](params)
            gold = {key: value for key, value in params.items() if key in DEFAULTS[family]}
            tasks.append({"family": family, "template_id": f"{family}-hard{index:02d}", "split": "hard",
                          "prompt": prompt, "params": gold, "frozen_at": f"2026-10-{3 + case % 25:02d}T12:00:00+00:00"})
    return tasks
